version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
    time: "21:00"
  open-pull-requests-limit: 10
  target-branch: master
  assignees:
  - vanitax
  ignore:
  - dependency-name: react-waypoint
    versions:
    - 10.0.0
    - 5.3.1
    - 9.0.3
  - dependency-name: css-loader
    versions:
    - 0.28.11
    - 5.0.2
    - 5.1.0
    - 5.1.1
    - 5.1.2
    - 5.1.3
    - 5.1.4
    - 5.2.0
    - 5.2.1
    - 5.2.2
    - 5.2.3
  - dependency-name: eslint
    versions:
    - 2.2.0
    - 7.20.0
    - 7.21.0
    - 7.22.0
    - 7.23.0
    - 7.24.0
  - dependency-name: eslint-plugin-react
    versions:
    - 5.2.2
    - 7.22.0
    - 7.23.0
    - 7.23.1
  - dependency-name: react
    versions:
    - 15.7.0
    - 17.0.1
  - dependency-name: babel-eslint
    versions:
    - 6.0.0-beta.6
  - dependency-name: node-sass
    versions:
    - 4.14.1
  - dependency-name: url-loader
    versions:
    - 4.1.0
  - dependency-name: file-loader
    versions:
    - 0.11.2
  - dependency-name: style-loader
    versions:
    - 0.23.1
